version: 2.1
jobs:
  build-frontend:
    docker:
      - image: circleci/node:16-alpine
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build frontend
          command: | 
            cd frontend
            npm install
            npm test
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: [frontend-build]




